export const port = process.env.PORT || 8000;
export const development = process.env.NODE_ENV === "development";
export const production = process.env.NODE_ENV === "production";
export const uri = process.env.MONGO_URI;
export const db_pass = process.env.DB_PASSWORD;
// export const client = process.env.CLIENT_URL;
// export const frontend = process.env.FRONTEND_URL;
// export const frontend_local = process.env.FRONTEND_LOCALHOST_URL;
// export const jwt_secret = process.env.JWT_ACCESS_TOKEN;
// export const jwt_secret_refresh = process.env.JWT_REFRESH_TOKEN;
// export const jwt_expire = process.env.JWT_EXPIRE_IN;
// export const jwt_expire_at = process.env.JWT_EXPIRE_AT;
// export const jwt_secret_session = process.env.SESSION_SECRET_KEY;
// export const cloudinary_name = process.env.CLOUDINARY_API_CLOUD_NAME;
// export const cloudinary_api_key = process.env.CLOUDINARY_API_KEY;
// export const cloudinary_api_secret = process.env.CLOUDINARY_API_SECRET_KEY;
// export const cloudinary = process.env.CLOUDINARY_API_URL;
// export const webhook = process.env.WEBHOOK_PASSWORD;
// export const uploadDir = process.env.UPLOAD_DIR;
// export const uploadUrl = process.env.UPLOAD_URL;
